# apps/hello_world/config.yaml
name: "Calculator"
description: "Calculator"
module: "app"           # The Python file (app.py)
icon: "./icon.png"
enabled: true
category: "examples"
type: "gui"             # "gui" or "script"
tags: []
version: "1.0"